### ISSUE TITLE
Атрибуты качества

### ISSUE THREAD

**Issue by steppbol** [DaniilPshenichny/BookReader#2]
Даниил, почему все элементы должны быть светлыми?

> 3.2.1.1 Требования к удобству использования
      1. Все элементы должны быть светлыми;

Мне, допустим, белый интерфейс неприятен, когда читаю ночью. Следовательно это не удобство, исправь, пожалуйста

**Comment by DaniilPshenichny** [comment]
Степан, это сделано для людей старших возрастов, которым легче смотреть на светлый интерфейс. Для пользователей Вашей категории будет реализован Night mode.
